# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Official

# run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on: 
  push:
    branches: [ "master", "dev" ]

env:
  GB_NUGET_TOKEN: ${{secrets.GB_NUGET_TOKEN}}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup BuildNumber
        id: setup_buildnumber
        run: .\.github\workflows\script\set-buildnumber.ps1 -refName ${{ github.ref_name }}
        shell: powershell

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Restore dependencies
        run: dotnet restore ./Service/SyZero.PiCar.sln

      - name: Build Service
        run: dotnet build --configuration Release ./Service/SyZero.PiCar.sln --no-restore

      - name: Build Client
        run: |
          cd ./Client
          npm install
          npm run build

      - name: Copy Artifact
        run: |
          Copy-Item -Path "./Client/build" -Destination "./PiCar/Client" -Recurse -Force
          Copy-Item -Path "./Service/SyZero.PiCar.Service/bin/*/net6.0" -Destination "./PiCar/Service" -Recurse -Force

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            ./PiCar/*

      - name: Get Release Note
        id: get_releasenote
        run: .\.github\workflows\script\get-releasenote.ps1 -version ${{ env.BUILD_BUILDNUMBER }}
        shell: powershell

      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ env.GB_NUGET_TOKEN }}
          tag: v${{ env.BUILD_BUILDNUMBER }}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          bodyFile: 'ReleaseNote.md'
          token: ${{ env.GB_NUGET_TOKEN }}
          prerelease: ${{ github.ref_name != 'master' }}
          tag: v${{ env.BUILD_BUILDNUMBER }}
          artifacts: "./PiCar"